echo " Website structure"
echo " Styling"
echo" Frontend JavaScript"
echo "e Bash control system"
echo " Node.js backend"
echo " Express server"
echo "JSON understanding"
echo " Environment variables "
echo" Dependency installation"
echo " Backend successfully running"
